services:
  backend:
    build:
      context: ./backend
    container_name: wordapp-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/wordapp
      - NODE_ENV=development
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-min-32-chars
      - JWT_EXPIRE=7d
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - wordapp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: wordapp-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wordapp-network
    restart: unless-stopped
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6
    container_name: wordapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wordapp-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  wordapp-network:
    driver: bridge
