version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: wordapp-backend-prod
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}  # MongoDB Atlas connection string
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=7d
    networks:
      - wordapp-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: wordapp-frontend-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - wordapp-network
    restart: always

networks:
  wordapp-network:
    driver: bridge

